import { useEffect, useState } from "react";

import { Card, FormField, Loader } from '../components';

const RenderCards = ({data,title}) => {
  if (data?.length > 0 ) {
    return data.map( (post)=> <Card key={post._id} {...post}/> )
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">
      {title}
    </h2>
  )
}
 

const Home = () => {

  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
 const [searchText ,setSearchText] = useState("");
  return (
    <section className="max-w-7xl mx-auto ">
      <div>
        <h1 className="font-extrabold text-[25px] text-[#222328] ">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w-[1500px]">
          Brouse through visually stunning images generated by AI-model
        </p>
      </div>
      <div className="mt-14">
        <FormField/>
      </div>
      <div className="mt-10">
        {loading ? (
        <div className="flex justify-center items-center">
          <Loader/>
        </div>):(
        <>
          {searchText && (
            <h2 className="font-medium text-[#666e75] text-xl mb-3">
              Showing results of <span className="text-[#222328]">{searchText}</span>
            </h2>
          )}
          <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 gap-3">
             {searchText ? (
             <RenderCards 
             data={[]} 
             title="no results found"
             />):
             (
              <RenderCards
              data={[]}
              title="No posts found"

              />
             )
            }
          </div>
        </>) }
      </div>
    </section>
  )
}

export default Home
